import { CodeNode } from '@flyde/core'
import { diagLog } from '../diag'

const dbg = (msg: string) => diagLog('DEBUG', 'Gemini', msg)

export const Gemini: CodeNode = {
  id: 'Gemini',
  displayName: 'Gemini',
  menuDisplayName: 'Gemini',
  icon: 'robot',
  defaultStyle: { color: '#1a73e8' },
  inputs: {
    apiKey: {
      description: 'Google AI Studio API key',
    },
    model: {
      description: 'Gemini model to use',
      editorType: 'select',
      editorTypeData: {
        options: [
          { value: 'gemini-2.5-flash',          label: 'Gemini 2.5 Flash (推奨)' },
          { value: 'gemini-2.5-pro',             label: 'Gemini 2.5 Pro' },
          { value: 'gemini-2.0-flash',           label: 'Gemini 2.0 Flash' },
          { value: 'gemini-2.0-flash-lite',      label: 'Gemini 2.0 Flash Lite' },
        ],
      },
    },
    prompt: {
      description: 'User prompt text',
    },
    systemInstruction: {
      description: 'System prompt defining AI role/behavior (optional)',
    },
    temperature: {
      description: 'Randomness 0.0–1.0 (lower = more deterministic)',
      editorType: 'number',
    },
    trigger: {
      description: 'Trigger (optional)',
    },
  },
  outputs: {
    response: {
      description: 'Text generated by Gemini',
    },
  },
  run: async ({ apiKey, model, prompt, systemInstruction, temperature }, { response }) => {
    if (!apiKey) throw new Error('Gemini: apiKey が指定されていません')
    if (!prompt)  throw new Error('Gemini: prompt が指定されていません')

    const selectedModel = model ? String(model) : 'gemini-2.5-flash'
    const tempVal = temperature != null ? Number(temperature) : 0.1

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${selectedModel}:generateContent?key=${apiKey}`
    const body: any = {
      contents: [{ parts: [{ text: String(prompt) }] }],
      generationConfig: { temperature: tempVal },
    }
    if (systemInstruction) {
      body.systemInstruction = { parts: [{ text: String(systemInstruction) }] }
    }
    dbg(`request: model=${selectedModel} prompt="${String(prompt).slice(0, 60)}"`)
    const fetchOpts = { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }
    let res = await fetch(url, fetchOpts)
    // 503/429 は一時的な過負荷。最大3回リトライ（2s, 4s 待機）
    for (let i = 1; !res.ok && (res.status === 503 || res.status === 429) && i <= 2; i++) {
      const wait = i * 2000
      dbg(`status=${res.status} retry ${i} in ${wait}ms`)
      await new Promise(r => setTimeout(r, wait))
      res = await fetch(url, fetchOpts)
    }
    if (!res.ok) {
      throw new Error(`Gemini API error ${res.status}: ${await res.text()}`)
    }
    const data = await res.json() as any
    const text: string | undefined = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim()
    if (text === undefined) throw new Error('Gemini: レスポンスにテキストがありません')
    dbg(`response: "${text.slice(0, 80)}"`)
    response.next(text)
  },
}
